title: Aveni Blog
description: Engineering notes and updates from the Aveni team.
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
future: false

baseurl: ""
url: "https://testblog.pages.dev"
