title: Aveni Blog
description: Engineering notes and updates from the Aveni team.
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
future: false

baseurl: "/testblog"
url: "https://mavenius.github.io"
